// Comprehensive India Data - All States, Union Territories, and Districts

export const allIndianStatesAndUTs = [
  // States
  { name: 'Andhra Pradesh', code: 'AP', type: 'state', capital: 'Amaravati' },
  { name: 'Arunachal Pradesh', code: 'AR', type: 'state', capital: 'Itanagar' },
  { name: 'Assam', code: 'AS', type: 'state', capital: 'Dispur' },
  { name: 'Bihar', code: 'BR', type: 'state', capital: 'Patna' },
  { name: 'Chhattisgarh', code: 'CG', type: 'state', capital: 'Raipur' },
  { name: 'Goa', code: 'GA', type: 'state', capital: 'Panaji' },
  { name: 'Gujarat', code: 'GJ', type: 'state', capital: 'Gandhinagar' },
  { name: 'Haryana', code: 'HR', type: 'state', capital: 'Chandigarh' },
  { name: 'Himachal Pradesh', code: 'HP', type: 'state', capital: 'Shimla' },
  { name: 'Jharkhand', code: 'JH', type: 'state', capital: 'Ranchi' },
  { name: 'Karnataka', code: 'KA', type: 'state', capital: 'Bengaluru' },
  { name: 'Kerala', code: 'KL', type: 'state', capital: 'Thiruvananthapuram' },
  { name: 'Madhya Pradesh', code: 'MP', type: 'state', capital: 'Bhopal' },
  { name: 'Maharashtra', code: 'MH', type: 'state', capital: 'Mumbai' },
  { name: 'Manipur', code: 'MN', type: 'state', capital: 'Imphal' },
  { name: 'Meghalaya', code: 'ML', type: 'state', capital: 'Shillong' },
  { name: 'Mizoram', code: 'MZ', type: 'state', capital: 'Aizawl' },
  { name: 'Nagaland', code: 'NL', type: 'state', capital: 'Kohima' },
  { name: 'Odisha', code: 'OR', type: 'state', capital: 'Bhubaneswar' },
  { name: 'Punjab', code: 'PB', type: 'state', capital: 'Chandigarh' },
  { name: 'Rajasthan', code: 'RJ', type: 'state', capital: 'Jaipur' },
  { name: 'Sikkim', code: 'SK', type: 'state', capital: 'Gangtok' },
  { name: 'Tamil Nadu', code: 'TN', type: 'state', capital: 'Chennai' },
  { name: 'Telangana', code: 'TS', type: 'state', capital: 'Hyderabad' },
  { name: 'Tripura', code: 'TR', type: 'state', capital: 'Agartala' },
  { name: 'Uttar Pradesh', code: 'UP', type: 'state', capital: 'Lucknow' },
  { name: 'Uttarakhand', code: 'UK', type: 'state', capital: 'Dehradun' },
  { name: 'West Bengal', code: 'WB', type: 'state', capital: 'Kolkata' },
  
  // Union Territories
  { name: 'Andaman and Nicobar Islands', code: 'AN', type: 'union-territory', capital: 'Port Blair' },
  { name: 'Chandigarh', code: 'CH', type: 'union-territory', capital: 'Chandigarh' },
  { name: 'Dadra and Nagar Haveli and Daman and Diu', code: 'DD', type: 'union-territory', capital: 'Daman' },
  { name: 'Delhi', code: 'DL', type: 'union-territory', capital: 'New Delhi' },
  { name: 'Jammu and Kashmir', code: 'JK', type: 'union-territory', capital: 'Srinagar (Summer), Jammu (Winter)' },
  { name: 'Ladakh', code: 'LA', type: 'union-territory', capital: 'Leh' },
  { name: 'Lakshadweep', code: 'LD', type: 'union-territory', capital: 'Kavaratti' },
  { name: 'Puducherry', code: 'PY', type: 'union-territory', capital: 'Puducherry' },
];

// All Indian Districts (750+ districts)
export const allIndianDistricts = [
  // Andhra Pradesh (26 districts)
  { name: 'Anantapur', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Chittoor', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'East Godavari', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Guntur', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Krishna', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Kurnool', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Nellore', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Prakasam', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Srikakulam', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Visakhapatnam', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Vizianagaram', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'West Godavari', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'YSR Kadapa', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Alluri Sitharama Raju', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Anakapalli', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Annamayya', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Bapatla', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Dr. B.R. Ambedkar Konaseema', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Eluru', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Kakinada', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Nandyal', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'NTR', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Palnadu', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Parvathipuram Manyam', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Sri Potti Sriramulu Nellore', state: 'Andhra Pradesh', stateCode: 'AP' },
  { name: 'Sri Sathya Sai', state: 'Andhra Pradesh', stateCode: 'AP' },

  // Arunachal Pradesh (25 districts)
  { name: 'Anjaw', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Changlang', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Dibang Valley', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'East Kameng', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'East Siang', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Kamle', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Kra Daadi', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Kurung Kumey', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Lepa Rada', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Lohit', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Longding', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Lower Dibang Valley', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Lower Siang', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Lower Subansiri', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Namsai', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Pakke Kessang', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Papum Pare', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Shi Yomi', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Siang', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Tawang', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Tirap', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Upper Siang', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'Upper Subansiri', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'West Kameng', state: 'Arunachal Pradesh', stateCode: 'AR' },
  { name: 'West Siang', state: 'Arunachal Pradesh', stateCode: 'AR' },

  // Assam (35 districts)
  { name: 'Baksa', state: 'Assam', stateCode: 'AS' },
  { name: 'Barpeta', state: 'Assam', stateCode: 'AS' },
  { name: 'Biswanath', state: 'Assam', stateCode: 'AS' },
  { name: 'Bongaigaon', state: 'Assam', stateCode: 'AS' },
  { name: 'Cachar', state: 'Assam', stateCode: 'AS' },
  { name: 'Charaideo', state: 'Assam', stateCode: 'AS' },
  { name: 'Chirang', state: 'Assam', stateCode: 'AS' },
  { name: 'Darrang', state: 'Assam', stateCode: 'AS' },
  { name: 'Dhemaji', state: 'Assam', stateCode: 'AS' },
  { name: 'Dhubri', state: 'Assam', stateCode: 'AS' },
  { name: 'Dibrugarh', state: 'Assam', stateCode: 'AS' },
  { name: 'Dima Hasao', state: 'Assam', stateCode: 'AS' },
  { name: 'Goalpara', state: 'Assam', stateCode: 'AS' },
  { name: 'Golaghat', state: 'Assam', stateCode: 'AS' },
  { name: 'Hailakandi', state: 'Assam', stateCode: 'AS' },
  { name: 'Hojai', state: 'Assam', stateCode: 'AS' },
  { name: 'Jorhat', state: 'Assam', stateCode: 'AS' },
  { name: 'Kamrup', state: 'Assam', stateCode: 'AS' },
  { name: 'Kamrup Metropolitan', state: 'Assam', stateCode: 'AS' },
  { name: 'Karbi Anglong', state: 'Assam', stateCode: 'AS' },
  { name: 'Karimganj', state: 'Assam', stateCode: 'AS' },
  { name: 'Kokrajhar', state: 'Assam', stateCode: 'AS' },
  { name: 'Lakhimpur', state: 'Assam', stateCode: 'AS' },
  { name: 'Majuli', state: 'Assam', stateCode: 'AS' },
  { name: 'Morigaon', state: 'Assam', stateCode: 'AS' },
  { name: 'Nagaon', state: 'Assam', stateCode: 'AS' },
  { name: 'Nalbari', state: 'Assam', stateCode: 'AS' },
  { name: 'Sivasagar', state: 'Assam', stateCode: 'AS' },
  { name: 'Sonitpur', state: 'Assam', stateCode: 'AS' },
  { name: 'South Salmara-Mankachar', state: 'Assam', stateCode: 'AS' },
  { name: 'Tinsukia', state: 'Assam', stateCode: 'AS' },
  { name: 'Udalguri', state: 'Assam', stateCode: 'AS' },
  { name: 'West Karbi Anglong', state: 'Assam', stateCode: 'AS' },
  { name: 'Bajali', state: 'Assam', stateCode: 'AS' },
  { name: 'Tamulpur', state: 'Assam', stateCode: 'AS' },

  // Bihar (38 districts)
  { name: 'Araria', state: 'Bihar', stateCode: 'BR' },
  { name: 'Arwal', state: 'Bihar', stateCode: 'BR' },
  { name: 'Aurangabad', state: 'Bihar', stateCode: 'BR' },
  { name: 'Banka', state: 'Bihar', stateCode: 'BR' },
  { name: 'Begusarai', state: 'Bihar', stateCode: 'BR' },
  { name: 'Bhagalpur', state: 'Bihar', stateCode: 'BR' },
  { name: 'Bhojpur', state: 'Bihar', stateCode: 'BR' },
  { name: 'Buxar', state: 'Bihar', stateCode: 'BR' },
  { name: 'Darbhanga', state: 'Bihar', stateCode: 'BR' },
  { name: 'East Champaran', state: 'Bihar', stateCode: 'BR' },
  { name: 'Gaya', state: 'Bihar', stateCode: 'BR' },
  { name: 'Gopalganj', state: 'Bihar', stateCode: 'BR' },
  { name: 'Jamui', state: 'Bihar', stateCode: 'BR' },
  { name: 'Jehanabad', state: 'Bihar', stateCode: 'BR' },
  { name: 'Kaimur', state: 'Bihar', stateCode: 'BR' },
  { name: 'Katihar', state: 'Bihar', stateCode: 'BR' },
  { name: 'Khagaria', state: 'Bihar', stateCode: 'BR' },
  { name: 'Kishanganj', state: 'Bihar', stateCode: 'BR' },
  { name: 'Lakhisarai', state: 'Bihar', stateCode: 'BR' },
  { name: 'Madhepura', state: 'Bihar', stateCode: 'BR' },
  { name: 'Madhubani', state: 'Bihar', stateCode: 'BR' },
  { name: 'Munger', state: 'Bihar', stateCode: 'BR' },
  { name: 'Muzaffarpur', state: 'Bihar', stateCode: 'BR' },
  { name: 'Nalanda', state: 'Bihar', stateCode: 'BR' },
  { name: 'Nawada', state: 'Bihar', stateCode: 'BR' },
  { name: 'Patna', state: 'Bihar', stateCode: 'BR' },
  { name: 'Purnia', state: 'Bihar', stateCode: 'BR' },
  { name: 'Rohtas', state: 'Bihar', stateCode: 'BR' },
  { name: 'Saharsa', state: 'Bihar', stateCode: 'BR' },
  { name: 'Samastipur', state: 'Bihar', stateCode: 'BR' },
  { name: 'Saran', state: 'Bihar', stateCode: 'BR' },
  { name: 'Sheikhpura', state: 'Bihar', stateCode: 'BR' },
  { name: 'Sheohar', state: 'Bihar', stateCode: 'BR' },
  { name: 'Sitamarhi', state: 'Bihar', stateCode: 'BR' },
  { name: 'Siwan', state: 'Bihar', stateCode: 'BR' },
  { name: 'Supaul', state: 'Bihar', stateCode: 'BR' },
  { name: 'Vaishali', state: 'Bihar', stateCode: 'BR' },
  { name: 'West Champaran', state: 'Bihar', stateCode: 'BR' },

  // Chhattisgarh (33 districts)
  { name: 'Balod', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Baloda Bazar', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Balrampur', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Bastar', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Bemetara', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Bijapur', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Bilaspur', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Dantewada', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Dhamtari', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Durg', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Gariaband', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Gaurela-Pendra-Marwahi', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Janjgir-Champa', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Jashpur', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Kabirdham', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Kanker', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Kondagaon', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Korba', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Koriya', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Mahasamund', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Manendragarh-Chirmiri-Bharatpur', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Mohla-Manpur-Ambagarh Chowki', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Mungeli', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Narayanpur', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Raigarh', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Raipur', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Rajnandgaon', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Sakti', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Sarangarh-Bilaigarh', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Sukma', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Surajpur', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Surguja', state: 'Chhattisgarh', stateCode: 'CG' },
  { name: 'Khairagarh-Chhuikhadan-Gandai', state: 'Chhattisgarh', stateCode: 'CG' },

  // Goa (2 districts)
  { name: 'North Goa', state: 'Goa', stateCode: 'GA' },
  { name: 'South Goa', state: 'Goa', stateCode: 'GA' },

  // Gujarat (33 districts)
  { name: 'Ahmedabad', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Amreli', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Anand', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Aravalli', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Banaskantha', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Bharuch', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Bhavnagar', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Botad', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Chhota Udaipur', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Dahod', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Dang', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Devbhoomi Dwarka', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Gandhinagar', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Gir Somnath', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Jamnagar', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Junagadh', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Kheda', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Kutch', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Mahisagar', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Mehsana', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Morbi', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Narmada', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Navsari', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Panchmahal', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Patan', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Porbandar', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Rajkot', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Sabarkantha', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Surat', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Surendranagar', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Tapi', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Vadodara', state: 'Gujarat', stateCode: 'GJ' },
  { name: 'Valsad', state: 'Gujarat', stateCode: 'GJ' },

  // Haryana (22 districts)
  { name: 'Ambala', state: 'Haryana', stateCode: 'HR' },
  { name: 'Bhiwani', state: 'Haryana', stateCode: 'HR' },
  { name: 'Charkhi Dadri', state: 'Haryana', stateCode: 'HR' },
  { name: 'Faridabad', state: 'Haryana', stateCode: 'HR' },
  { name: 'Fatehabad', state: 'Haryana', stateCode: 'HR' },
  { name: 'Gurugram', state: 'Haryana', stateCode: 'HR' },
  { name: 'Hisar', state: 'Haryana', stateCode: 'HR' },
  { name: 'Jhajjar', state: 'Haryana', stateCode: 'HR' },
  { name: 'Jind', state: 'Haryana', stateCode: 'HR' },
  { name: 'Kaithal', state: 'Haryana', stateCode: 'HR' },
  { name: 'Karnal', state: 'Haryana', stateCode: 'HR' },
  { name: 'Kurukshetra', state: 'Haryana', stateCode: 'HR' },
  { name: 'Mahendragarh', state: 'Haryana', stateCode: 'HR' },
  { name: 'Nuh', state: 'Haryana', stateCode: 'HR' },
  { name: 'Palwal', state: 'Haryana', stateCode: 'HR' },
  { name: 'Panchkula', state: 'Haryana', stateCode: 'HR' },
  { name: 'Panipat', state: 'Haryana', stateCode: 'HR' },
  { name: 'Rewari', state: 'Haryana', stateCode: 'HR' },
  { name: 'Rohtak', state: 'Haryana', stateCode: 'HR' },
  { name: 'Sirsa', state: 'Haryana', stateCode: 'HR' },
  { name: 'Sonipat', state: 'Haryana', stateCode: 'HR' },
  { name: 'Yamunanagar', state: 'Haryana', stateCode: 'HR' },

  // Himachal Pradesh (12 districts)
  { name: 'Bilaspur', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Chamba', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Hamirpur', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Kangra', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Kinnaur', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Kullu', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Lahaul and Spiti', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Mandi', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Shimla', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Sirmaur', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Solan', state: 'Himachal Pradesh', stateCode: 'HP' },
  { name: 'Una', state: 'Himachal Pradesh', stateCode: 'HP' },

  // Jharkhand (24 districts)
  { name: 'Bokaro', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Chatra', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Deoghar', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Dhanbad', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Dumka', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'East Singhbhum', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Garhwa', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Giridih', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Godda', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Gumla', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Hazaribagh', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Jamtara', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Khunti', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Koderma', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Latehar', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Lohardaga', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Pakur', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Palamu', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Ramgarh', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Ranchi', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Sahibganj', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Seraikela Kharsawan', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'Simdega', state: 'Jharkhand', stateCode: 'JH' },
  { name: 'West Singhbhum', state: 'Jharkhand', stateCode: 'JH' },

  // Karnataka (31 districts)
  { name: 'Bagalkot', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Bangalore Rural', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Bangalore Urban', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Belgaum', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Bellary', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Bidar', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Chamarajanagar', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Chikkaballapur', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Chikkamagaluru', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Chitradurga', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Dakshina Kannada', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Davanagere', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Dharwad', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Gadag', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Hassan', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Haveri', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Kalaburagi', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Kodagu', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Kolar', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Koppal', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Mandya', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Mysore', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Raichur', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Ramanagara', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Shimoga', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Tumkur', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Udupi', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Uttara Kannada', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Vijayapura', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Yadgir', state: 'Karnataka', stateCode: 'KA' },
  { name: 'Vijayanagara', state: 'Karnataka', stateCode: 'KA' },

  // Kerala (14 districts)
  { name: 'Alappuzha', state: 'Kerala', stateCode: 'KL' },
  { name: 'Ernakulam', state: 'Kerala', stateCode: 'KL' },
  { name: 'Idukki', state: 'Kerala', stateCode: 'KL' },
  { name: 'Kannur', state: 'Kerala', stateCode: 'KL' },
  { name: 'Kasaragod', state: 'Kerala', stateCode: 'KL' },
  { name: 'Kollam', state: 'Kerala', stateCode: 'KL' },
  { name: 'Kottayam', state: 'Kerala', stateCode: 'KL' },
  { name: 'Kozhikode', state: 'Kerala', stateCode: 'KL' },
  { name: 'Malappuram', state: 'Kerala', stateCode: 'KL' },
  { name: 'Palakkad', state: 'Kerala', stateCode: 'KL' },
  { name: 'Pathanamthitta', state: 'Kerala', stateCode: 'KL' },
  { name: 'Thiruvananthapuram', state: 'Kerala', stateCode: 'KL' },
  { name: 'Thrissur', state: 'Kerala', stateCode: 'KL' },
  { name: 'Wayanad', state: 'Kerala', stateCode: 'KL' },

  // Madhya Pradesh (55 districts)
  { name: 'Agar Malwa', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Alirajpur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Anuppur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Ashoknagar', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Balaghat', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Barwani', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Betul', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Bhind', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Bhopal', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Burhanpur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Chhatarpur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Chhindwara', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Damoh', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Datia', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Dewas', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Dhar', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Dindori', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Guna', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Gwalior', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Harda', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Hoshangabad', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Indore', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Jabalpur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Jhabua', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Katni', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Khandwa', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Khargone', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Mandla', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Mandsaur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Morena', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Narsinghpur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Neemuch', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Niwari', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Panna', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Raisen', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Rajgarh', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Ratlam', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Rewa', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Sagar', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Satna', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Sehore', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Seoni', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Shahdol', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Shajapur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Sheopur', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Shivpuri', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Sidhi', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Singrauli', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Tikamgarh', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Ujjain', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Umaria', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Vidisha', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Maihar', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Mauganj', state: 'Madhya Pradesh', stateCode: 'MP' },
  { name: 'Nagda', state: 'Madhya Pradesh', stateCode: 'MP' },

  // Maharashtra (36 districts)
  { name: 'Ahmednagar', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Akola', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Amravati', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Aurangabad', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Beed', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Bhandara', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Buldhana', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Chandrapur', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Dhule', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Gadchiroli', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Gondia', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Hingoli', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Jalgaon', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Jalna', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Kolhapur', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Latur', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Mumbai City', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Mumbai Suburban', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Nagpur', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Nanded', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Nandurbar', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Nashik', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Osmanabad', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Palghar', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Parbhani', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Pune', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Raigad', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Ratnagiri', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Sangli', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Satara', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Sindhudurg', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Solapur', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Thane', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Wardha', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Washim', state: 'Maharashtra', stateCode: 'MH' },
  { name: 'Yavatmal', state: 'Maharashtra', stateCode: 'MH' },

  // Manipur (16 districts)
  { name: 'Bishnupur', state: 'Manipur', stateCode: 'MN' },
  { name: 'Chandel', state: 'Manipur', stateCode: 'MN' },
  { name: 'Churachandpur', state: 'Manipur', stateCode: 'MN' },
  { name: 'Imphal East', state: 'Manipur', stateCode: 'MN' },
  { name: 'Imphal West', state: 'Manipur', stateCode: 'MN' },
  { name: 'Jiribam', state: 'Manipur', stateCode: 'MN' },
  { name: 'Kakching', state: 'Manipur', stateCode: 'MN' },
  { name: 'Kamjong', state: 'Manipur', stateCode: 'MN' },
  { name: 'Kangpokpi', state: 'Manipur', stateCode: 'MN' },
  { name: 'Noney', state: 'Manipur', stateCode: 'MN' },
  { name: 'Pherzawl', state: 'Manipur', stateCode: 'MN' },
  { name: 'Senapati', state: 'Manipur', stateCode: 'MN' },
  { name: 'Tamenglong', state: 'Manipur', stateCode: 'MN' },
  { name: 'Tengnoupal', state: 'Manipur', stateCode: 'MN' },
  { name: 'Thoubal', state: 'Manipur', stateCode: 'MN' },
  { name: 'Ukhrul', state: 'Manipur', stateCode: 'MN' },

  // Meghalaya (12 districts)
  { name: 'East Garo Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'East Jaintia Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'East Khasi Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'Eastern West Khasi Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'North Garo Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'Ri Bhoi', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'South Garo Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'South West Garo Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'South West Khasi Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'West Garo Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'West Jaintia Hills', state: 'Meghalaya', stateCode: 'ML' },
  { name: 'West Khasi Hills', state: 'Meghalaya', stateCode: 'ML' },

  // Mizoram (11 districts)
  { name: 'Aizawl', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Champhai', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Hnahthial', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Khawzawl', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Kolasib', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Lawngtlai', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Lunglei', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Mamit', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Saiha', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Saitual', state: 'Mizoram', stateCode: 'MZ' },
  { name: 'Serchhip', state: 'Mizoram', stateCode: 'MZ' },

  // Nagaland (16 districts)
  { name: 'Chumukedima', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Dimapur', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Kiphire', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Kohima', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Longleng', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Mokokchung', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Mon', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Niuland', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Noklak', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Peren', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Phek', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Shamator', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Tseminyu', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Tuensang', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Wokha', state: 'Nagaland', stateCode: 'NL' },
  { name: 'Zunheboto', state: 'Nagaland', stateCode: 'NL' },

  // Odisha (30 districts)
  { name: 'Angul', state: 'Odisha', stateCode: 'OR' },
  { name: 'Balangir', state: 'Odisha', stateCode: 'OR' },
  { name: 'Balasore', state: 'Odisha', stateCode: 'OR' },
  { name: 'Bargarh', state: 'Odisha', stateCode: 'OR' },
  { name: 'Bhadrak', state: 'Odisha', stateCode: 'OR' },
  { name: 'Boudh', state: 'Odisha', stateCode: 'OR' },
  { name: 'Cuttack', state: 'Odisha', stateCode: 'OR' },
  { name: 'Deogarh', state: 'Odisha', stateCode: 'OR' },
  { name: 'Dhenkanal', state: 'Odisha', stateCode: 'OR' },
  { name: 'Gajapati', state: 'Odisha', stateCode: 'OR' },
  { name: 'Ganjam', state: 'Odisha', stateCode: 'OR' },
  { name: 'Jagatsinghpur', state: 'Odisha', stateCode: 'OR' },
  { name: 'Jajpur', state: 'Odisha', stateCode: 'OR' },
  { name: 'Jharsuguda', state: 'Odisha', stateCode: 'OR' },
  { name: 'Kalahandi', state: 'Odisha', stateCode: 'OR' },
  { name: 'Kandhamal', state: 'Odisha', stateCode: 'OR' },
  { name: 'Kendrapara', state: 'Odisha', stateCode: 'OR' },
  { name: 'Kendujhar', state: 'Odisha', stateCode: 'OR' },
  { name: 'Khordha', state: 'Odisha', stateCode: 'OR' },
  { name: 'Koraput', state: 'Odisha', stateCode: 'OR' },
  { name: 'Malkangiri', state: 'Odisha', stateCode: 'OR' },
  { name: 'Mayurbhanj', state: 'Odisha', stateCode: 'OR' },
  { name: 'Nabarangpur', state: 'Odisha', stateCode: 'OR' },
  { name: 'Nayagarh', state: 'Odisha', stateCode: 'OR' },
  { name: 'Nuapada', state: 'Odisha', stateCode: 'OR' },
  { name: 'Puri', state: 'Odisha', stateCode: 'OR' },
  { name: 'Rayagada', state: 'Odisha', stateCode: 'OR' },
  { name: 'Sambalpur', state: 'Odisha', stateCode: 'OR' },
  { name: 'Subarnapur', state: 'Odisha', stateCode: 'OR' },
  { name: 'Sundargarh', state: 'Odisha', stateCode: 'OR' },

  // Punjab (23 districts)
  { name: 'Amritsar', state: 'Punjab', stateCode: 'PB' },
  { name: 'Barnala', state: 'Punjab', stateCode: 'PB' },
  { name: 'Bathinda', state: 'Punjab', stateCode: 'PB' },
  { name: 'Faridkot', state: 'Punjab', stateCode: 'PB' },
  { name: 'Fatehgarh Sahib', state: 'Punjab', stateCode: 'PB' },
  { name: 'Fazilka', state: 'Punjab', stateCode: 'PB' },
  { name: 'Ferozepur', state: 'Punjab', stateCode: 'PB' },
  { name: 'Gurdaspur', state: 'Punjab', stateCode: 'PB' },
  { name: 'Hoshiarpur', state: 'Punjab', stateCode: 'PB' },
  { name: 'Jalandhar', state: 'Punjab', stateCode: 'PB' },
  { name: 'Kapurthala', state: 'Punjab', stateCode: 'PB' },
  { name: 'Ludhiana', state: 'Punjab', stateCode: 'PB' },
  { name: 'Mansa', state: 'Punjab', stateCode: 'PB' },
  { name: 'Moga', state: 'Punjab', stateCode: 'PB' },
  { name: 'Mohali', state: 'Punjab', stateCode: 'PB' },
  { name: 'Muktsar', state: 'Punjab', stateCode: 'PB' },
  { name: 'Pathankot', state: 'Punjab', stateCode: 'PB' },
  { name: 'Patiala', state: 'Punjab', stateCode: 'PB' },
  { name: 'Rupnagar', state: 'Punjab', stateCode: 'PB' },
  { name: 'Sangrur', state: 'Punjab', stateCode: 'PB' },
  { name: 'Shaheed Bhagat Singh Nagar', state: 'Punjab', stateCode: 'PB' },
  { name: 'Tarn Taran', state: 'Punjab', stateCode: 'PB' },
  { name: 'Malerkotla', state: 'Punjab', stateCode: 'PB' },

  // Rajasthan (50 districts)
  { name: 'Ajmer', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Alwar', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Anupgarh', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Balotra', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Banswara', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Baran', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Barmer', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Beawar', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Bharatpur', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Bhilwara', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Bikaner', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Bundi', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Chittorgarh', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Churu', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Dausa', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Deeg', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Dholpur', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Didwana-Kuchaman', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Dudu', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Dungarpur', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Gangapur City', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Hanumangarh', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Jaipur', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Jaisalmer', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Jalore', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Jhalawar', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Jhunjhunu', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Jodhpur', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Karauli', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Kekri', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Khaerthal-Tijara', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Kota', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Kotputli-Behror', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Nagaur', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Neem ka Thana', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Pali', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Phalodi', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Pratapgarh', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Rajsamand', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Salumbar', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Sanchore', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Sawai Madhopur', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Shahpura', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Sikar', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Sirohi', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Sri Ganganagar', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Tonk', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Udaipur', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Jaipur Rural', state: 'Rajasthan', stateCode: 'RJ' },
  { name: 'Jodhpur Rural', state: 'Rajasthan', stateCode: 'RJ' },

  // Sikkim (6 districts)
  { name: 'East Sikkim', state: 'Sikkim', stateCode: 'SK' },
  { name: 'North Sikkim', state: 'Sikkim', stateCode: 'SK' },
  { name: 'Pakyong', state: 'Sikkim', stateCode: 'SK' },
  { name: 'Soreng', state: 'Sikkim', stateCode: 'SK' },
  { name: 'South Sikkim', state: 'Sikkim', stateCode: 'SK' },
  { name: 'West Sikkim', state: 'Sikkim', stateCode: 'SK' },

  // Tamil Nadu (38 districts)
  { name: 'Ariyalur', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Chengalpattu', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Chennai', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Coimbatore', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Cuddalore', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Dharmapuri', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Dindigul', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Erode', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Kallakurichi', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Kanchipuram', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Kanyakumari', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Karur', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Krishnagiri', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Madurai', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Mayiladuthurai', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Nagapattinam', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Namakkal', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Nilgiris', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Perambalur', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Pudukkottai', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Ramanathapuram', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Ranipet', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Salem', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Sivaganga', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Tenkasi', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Thanjavur', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Theni', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Thoothukudi', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Tiruchirappalli', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Tirunelveli', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Tirupattur', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Tiruppur', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Tiruvallur', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Tiruvannamalai', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Tiruvarur', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Vellore', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Viluppuram', state: 'Tamil Nadu', stateCode: 'TN' },
  { name: 'Virudhunagar', state: 'Tamil Nadu', stateCode: 'TN' },

  // Telangana (33 districts)
  { name: 'Adilabad', state: 'Telangana', stateCode: 'TS' },
  { name: 'Bhadradri Kothagudem', state: 'Telangana', stateCode: 'TS' },
  { name: 'Hanamkonda', state: 'Telangana', stateCode: 'TS' },
  { name: 'Hyderabad', state: 'Telangana', stateCode: 'TS' },
  { name: 'Jagtial', state: 'Telangana', stateCode: 'TS' },
  { name: 'Jangaon', state: 'Telangana', stateCode: 'TS' },
  { name: 'Jayashankar Bhupalpally', state: 'Telangana', stateCode: 'TS' },
  { name: 'Jogulamba Gadwal', state: 'Telangana', stateCode: 'TS' },
  { name: 'Kamareddy', state: 'Telangana', stateCode: 'TS' },
  { name: 'Karimnagar', state: 'Telangana', stateCode: 'TS' },
  { name: 'Khammam', state: 'Telangana', stateCode: 'TS' },
  { name: 'Komaram Bheem', state: 'Telangana', stateCode: 'TS' },
  { name: 'Mahabubabad', state: 'Telangana', stateCode: 'TS' },
  { name: 'Mahabubnagar', state: 'Telangana', stateCode: 'TS' },
  { name: 'Mancherial', state: 'Telangana', stateCode: 'TS' },
  { name: 'Medak', state: 'Telangana', stateCode: 'TS' },
  { name: 'Medchal-Malkajgiri', state: 'Telangana', stateCode: 'TS' },
  { name: 'Mulugu', state: 'Telangana', stateCode: 'TS' },
  { name: 'Nagarkurnool', state: 'Telangana', stateCode: 'TS' },
  { name: 'Nalgonda', state: 'Telangana', stateCode: 'TS' },
  { name: 'Narayanpet', state: 'Telangana', stateCode: 'TS' },
  { name: 'Nirmal', state: 'Telangana', stateCode: 'TS' },
  { name: 'Nizamabad', state: 'Telangana', stateCode: 'TS' },
  { name: 'Peddapalli', state: 'Telangana', stateCode: 'TS' },
  { name: 'Rajanna Sircilla', state: 'Telangana', stateCode: 'TS' },
  { name: 'Ranga Reddy', state: 'Telangana', stateCode: 'TS' },
  { name: 'Sangareddy', state: 'Telangana', stateCode: 'TS' },
  { name: 'Siddipet', state: 'Telangana', stateCode: 'TS' },
  { name: 'Suryapet', state: 'Telangana', stateCode: 'TS' },
  { name: 'Vikarabad', state: 'Telangana', stateCode: 'TS' },
  { name: 'Wanaparthy', state: 'Telangana', stateCode: 'TS' },
  { name: 'Warangal', state: 'Telangana', stateCode: 'TS' },
  { name: 'Yadadri Bhuvanagiri', state: 'Telangana', stateCode: 'TS' },

  // Tripura (8 districts)
  { name: 'Dhalai', state: 'Tripura', stateCode: 'TR' },
  { name: 'Gomati', state: 'Tripura', stateCode: 'TR' },
  { name: 'Khowai', state: 'Tripura', stateCode: 'TR' },
  { name: 'North Tripura', state: 'Tripura', stateCode: 'TR' },
  { name: 'Sepahijala', state: 'Tripura', stateCode: 'TR' },
  { name: 'South Tripura', state: 'Tripura', stateCode: 'TR' },
  { name: 'Unakoti', state: 'Tripura', stateCode: 'TR' },
  { name: 'West Tripura', state: 'Tripura', stateCode: 'TR' },

  // Uttar Pradesh (75 districts)
  { name: 'Agra', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Aligarh', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Ambedkar Nagar', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Amethi', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Amroha', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Auraiya', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Ayodhya', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Azamgarh', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Baghpat', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Bahraich', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Ballia', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Balrampur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Banda', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Barabanki', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Bareilly', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Basti', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Bhadohi', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Bijnor', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Budaun', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Bulandshahr', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Chandauli', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Chitrakoot', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Deoria', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Etah', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Etawah', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Farrukhabad', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Fatehpur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Firozabad', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Gautam Buddha Nagar', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Ghaziabad', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Ghazipur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Gonda', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Gorakhpur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Hamirpur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Hapur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Hardoi', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Hathras', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Jalaun', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Jaunpur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Jhansi', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Kannauj', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Kanpur Dehat', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Kanpur Nagar', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Kasganj', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Kaushambi', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Kushinagar', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Lakhimpur Kheri', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Lalitpur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Lucknow', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Maharajganj', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Mahoba', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Mainpuri', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Mathura', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Mau', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Meerut', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Mirzapur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Moradabad', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Muzaffarnagar', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Pilibhit', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Pratapgarh', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Prayagraj', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Raebareli', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Rampur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Saharanpur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Sambhal', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Sant Kabir Nagar', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Shahjahanpur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Shamli', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Shrawasti', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Siddharthnagar', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Sitapur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Sonbhadra', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Sultanpur', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Unnao', state: 'Uttar Pradesh', stateCode: 'UP' },
  { name: 'Varanasi', state: 'Uttar Pradesh', stateCode: 'UP' },

  // Uttarakhand (13 districts)
  { name: 'Almora', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Bageshwar', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Chamoli', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Champawat', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Dehradun', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Haridwar', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Nainital', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Pauri Garhwal', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Pithoragarh', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Rudraprayag', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Tehri Garhwal', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Udham Singh Nagar', state: 'Uttarakhand', stateCode: 'UK' },
  { name: 'Uttarkashi', state: 'Uttarakhand', stateCode: 'UK' },

  // West Bengal (23 districts)
  { name: 'Alipurduar', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Bankura', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Birbhum', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Cooch Behar', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Dakshin Dinajpur', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Darjeeling', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Hooghly', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Howrah', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Jalpaiguri', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Jhargram', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Kalimpong', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Kolkata', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Malda', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Murshidabad', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Nadia', state: 'West Bengal', stateCode: 'WB' },
  { name: 'North 24 Parganas', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Paschim Bardhaman', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Paschim Medinipur', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Purba Bardhaman', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Purba Medinipur', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Purulia', state: 'West Bengal', stateCode: 'WB' },
  { name: 'South 24 Parganas', state: 'West Bengal', stateCode: 'WB' },
  { name: 'Uttar Dinajpur', state: 'West Bengal', stateCode: 'WB' },

  // Union Territories
  // Andaman and Nicobar Islands (3 districts)
  { name: 'Nicobar', state: 'Andaman and Nicobar Islands', stateCode: 'AN' },
  { name: 'North and Middle Andaman', state: 'Andaman and Nicobar Islands', stateCode: 'AN' },
  { name: 'South Andaman', state: 'Andaman and Nicobar Islands', stateCode: 'AN' },

  // Chandigarh (1 district)
  { name: 'Chandigarh', state: 'Chandigarh', stateCode: 'CH' },

  // Dadra and Nagar Haveli and Daman and Diu (3 districts)
  { name: 'Dadra and Nagar Haveli', state: 'Dadra and Nagar Haveli and Daman and Diu', stateCode: 'DD' },
  { name: 'Daman', state: 'Dadra and Nagar Haveli and Daman and Diu', stateCode: 'DD' },
  { name: 'Diu', state: 'Dadra and Nagar Haveli and Daman and Diu', stateCode: 'DD' },

  // Delhi (11 districts)
  { name: 'Central Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'East Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'New Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'North Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'North East Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'North West Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'Shahdara', state: 'Delhi', stateCode: 'DL' },
  { name: 'South Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'South East Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'South West Delhi', state: 'Delhi', stateCode: 'DL' },
  { name: 'West Delhi', state: 'Delhi', stateCode: 'DL' },

  // Jammu and Kashmir (20 districts)
  { name: 'Anantnag', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Bandipora', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Baramulla', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Budgam', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Doda', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Ganderbal', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Jammu', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Kathua', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Kishtwar', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Kulgam', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Kupwara', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Poonch', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Pulwama', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Rajouri', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Ramban', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Reasi', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Samba', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Shopian', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Srinagar', state: 'Jammu and Kashmir', stateCode: 'JK' },
  { name: 'Udhampur', state: 'Jammu and Kashmir', stateCode: 'JK' },

  // Ladakh (2 districts)
  { name: 'Kargil', state: 'Ladakh', stateCode: 'LA' },
  { name: 'Leh', state: 'Ladakh', stateCode: 'LA' },

  // Lakshadweep (1 district)
  { name: 'Lakshadweep', state: 'Lakshadweep', stateCode: 'LD' },

  // Puducherry (4 districts)
  { name: 'Karaikal', state: 'Puducherry', stateCode: 'PY' },
  { name: 'Mahe', state: 'Puducherry', stateCode: 'PY' },
  { name: 'Puducherry', state: 'Puducherry', stateCode: 'PY' },
  { name: 'Yanam', state: 'Puducherry', stateCode: 'PY' },
];
